services:
  db:
    image: mariadb:10.4
    container_name: 'db'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  
  server:
    build: 
      context: .
    container_name: 'server'
    ports:
      - '8080:8080'
    depends_on:
      - db
  
volumes:
  my-db:

    
    